[package]
name = "simple-db-rust"
version = "0.1.6"
authors = ["XiaochenCui <jcnlcxc.new@gmail.com>"]
edition = "2018"
description = "A simple database writing in rust, inspired from mit 6.830"
license = "BSD-3-Clause"
readme = "README.md"
homepage = "https://crates.io/crates/simple-db-rust"
repository = "https://github.com/XiaochenCui/simple-db-rust/"
documentation = "https://docs.rs/simple-db-rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
log = "0.4.8"
env_logger = "0.7.1"
bit-vec = "0.6.2"
lazy_static = "1.4.0"
once_cell = "1.4.0"
hex = "0.4.2"
itertools = "0.9.0"
