pub fn print_features() {
    if cfg!(feature = "benchmark") {
        log::debug!("benchmark enabled");
    } else {
        log::debug!("--- benchmark disabled ---");
    }

    // === [COMPILATION OPTIONS START] (generated by make gen, do not edit) ===
    if cfg!(feature = "tree_latch") {
        log::debug!("tree_latch enabled");
    } else {
        log::debug!("--- tree_latch disabled ---");
    }

    if cfg!(feature = "page_latch") {
        log::debug!("page_latch enabled");
    } else {
        log::debug!("--- page_latch disabled ---");
    }

    if cfg!(feature = "aries_steal") {
        log::debug!("aries_steal enabled");
    } else {
        log::debug!("--- aries_steal disabled ---");
    }

    if cfg!(feature = "aries_no_steal") {
        log::debug!("aries_no_steal enabled");
    } else {
        log::debug!("--- aries_no_steal disabled ---");
    }

    if cfg!(feature = "aries_force") {
        log::debug!("aries_force enabled");
    } else {
        log::debug!("--- aries_force disabled ---");
    }

    if cfg!(feature = "aries_no_force") {
        log::debug!("aries_no_force enabled");
    } else {
        log::debug!("--- aries_no_force disabled ---");
    }

    if cfg!(feature = "read_uncommitted") {
        log::debug!("read_uncommitted enabled");
    } else {
        log::debug!("--- read_uncommitted disabled ---");
    }

    if cfg!(feature = "read_committed") {
        log::debug!("read_committed enabled");
    } else {
        log::debug!("--- read_committed disabled ---");
    }

    if cfg!(feature = "repeatable_read") {
        log::debug!("repeatable_read enabled");
    } else {
        log::debug!("--- repeatable_read disabled ---");
    }

    if cfg!(feature = "serializable") {
        log::debug!("serializable enabled");
    } else {
        log::debug!("--- serializable disabled ---");
    }

    // === [COMPILATION OPTIONS END] (generated by make gen, do not edit) ===
}
