pub fn print_features() {
    // === [COMPILATION OPTIONS START] (generated by make gen, do not edit) ===

    // === [COMPILATION OPTIONS END] (generated by make gen, do not edit) ===
    if cfg!(feature = "benchmark") {
        log::debug!("benchmark enabled");
    } else {
        log::debug!("--- benchmark disabled ---");
    }
}
