# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Define nodes with hostnames and IPs
  nodes = [
    { hostname: "asia", ip: "192.168.56.110" },
    { hostname: "europe", ip: "192.168.56.120" },
    { hostname: "america", ip: "192.168.56.130" }
  ]

  nodes.each do |node_config|
    config.vm.define node_config[:hostname] do |node|
      node.vm.box = "bento/ubuntu-24.04"

      node.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = 2
      end

      # use the default key: ~/.vagrant.d/insecure_private_key
      node.ssh.insert_key = false

      # set private ip
      node.vm.network "private_network", ip: node_config[:ip]

      # set hostname
      node.vm.hostname = node_config[:hostname]

      # set DNS entry
      node.vm.provision "shell", inline: <<-SHELL
        echo "#{nodes.map { |n| "#{n[:ip]} #{n[:hostname]}" }.join("\n")}" | sudo tee -a /etc/hosts
      SHELL

      # install necessary packages
      node.vm.provision "shell", inline: <<-SHELL
        # set "noninteractive" to avoid error:
        # dpkg-preconfigure: unable to re-open stdin: No such file or directory
        sudo DEBIAN_FRONTEND=noninteractive apt-get update

        # ifconfig
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y net-tools
      SHELL

      # set timezone to PST so its log's timestamp align with the host machine
      node.vm.provision "shell", inline: <<-SHELL
        sudo timedatectl set-timezone America/Los_Angeles
      SHELL

      # setup chrony for time synchronization
      node.vm.provision "shell", inline: <<-SHELL
        sudo DEBIAN_FRONTEND=noninteractive apt-get -y install chrony
      SHELL
    end
  end
end
  