env:
  CARGO_TERM_COLOR: always
jobs:
  test_page_latch_aries_no_steal_aries_force:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: make test_page_latch_aries_no_steal_aries_force
  test_page_latch_aries_no_steal_aries_no_force:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: make test_page_latch_aries_no_steal_aries_no_force
  test_page_latch_aries_steal_aries_force:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: make test_page_latch_aries_steal_aries_force
  test_page_latch_aries_steal_aries_no_force:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: make test_page_latch_aries_steal_aries_no_force
  test_tree_latch_aries_no_steal_aries_force:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: make test_tree_latch_aries_no_steal_aries_force
  test_tree_latch_aries_no_steal_aries_no_force:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: make test_tree_latch_aries_no_steal_aries_no_force
  test_tree_latch_aries_steal_aries_force:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: make test_tree_latch_aries_steal_aries_force
  test_tree_latch_aries_steal_aries_no_force:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: make test_tree_latch_aries_steal_aries_no_force
name: test
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
