name: test (page_latch, aries_no_steal, aries_force, serializable)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    # the job will be killed and marked as "failed" after running for 3 minutes
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        # use bash instead of sh, so we can use bash options
        shell: bash
        run: |
          cargo version
          make test_page_latch_aries_no_steal_aries_force_serializable
